name: deployment

on:
  workflow_call

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml
  
  test:
    needs: setup
    uses: ./.github/workflows/tests.yaml
  
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: terraform plan
